# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NeverSitUpTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NeverSitUpTest 
  pod 'Alamofire', '~> 5.0'

  target 'NeverSitUpTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NeverSitUpTestUITests' do
    # Pods for testing
  end

end
